services:
  jenkins: 
    image: jenkins/jenkins:lts-jdk17 
    privileged: true 
    user: root 
    ports: 
      - 8080:8080
    container_name: jenkins 
    volumes: 
      - ~/jenkins:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/bin/docker:/usr/bin/docker
